### ISSUE TITLE
Here is one that works with WIFI

### ISSUE THREAD

**Issue by tomatotxt** [Hermivore8151/Bindable-LagSwitch#2]
https://github.com/mattsays/ProjectCherry

**Comment by Hermivore8151** [comment]
thanks! might be worth for me to reverse engineer the lagswitch to see if i can get it to work

**Comment by Hermivore8151** [comment]
Github page was deleted for projectcherry, sorry all!

**Comment by daniel4-scratch** [comment]
Sorry for bumping an old issue. But i find when i use the python source it does cut the wifi connection

**Comment by Hermivore8151** [comment]
No worries! The lagswitch itself takes a while to reconnect because windows is quite slow for disconnecting and reconnecting to wifi
it works, its just slow
if you mean that it shouldnt cut the wifi connection, then yeah, its meant to
it calls the cmd call "ipconfig /release" and "/renew" to act as a way of litterally just disconnecting and reconnecting

**Comment by tomatotxt** [comment]
I think if you use firewall rules then it doesn't disconnect from the wifi but still cuts of the connection cause you just tell the firewall to block everything and then you can toggle quicker, not sure tho
> No worries! The lagswitch itself takes a while to reconnect because windows is quite slow for disconnecting and reconnecting to wifi
> it works, its just slow
> if you mean that it shouldnt cut the wifi connection, then yeah, its meant to
> it calls the cmd call "ipconfig /release" and "/renew" to act as a way of litterally just disconnecting and reconnecting
